### ISSUE TITLE
Search shortcut for Windows is broken

### ISSUE THREAD

**Issue by kiaking** [vuejs/theme#35]
Need to fix this one. The CTRL icon(?) is not looking fantastic.

<img width="316" alt="Screen Shot 2021-11-24 at 22 04 36" src="https://user-images.githubusercontent.com/3753672/143243823-d32eb2fb-8c5b-4342-a630-6d28d379bed3.png">

**Comment by Jinjiang** [comment]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/206848/182455372-d49c7d31-d5a9-4787-8343-3835ecf03d09.png">

Seems it's normal now and the shortcut works on my Windows laptop.

@kiaking would you mind a double-check? :-)

**Comment by Jinjiang** [comment]
I found the main difference is `@vue/theme` uses `<span>`s rather than `<kbd>`s to render the keys. As a result, it shows different styles before and after the real search box is loaded.

Since the code is not the same as the default theme of vitepress (this could be another separated topic), I think the minimized solution is changing `span`s into `kbd`s. As I tested it worked. PR created. #71

**Comment by yyx990803** [comment]
Closing as it seems to have been fixed
